name: build

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:
  push:
    branches: main


jobs:
  call_python_workflows:
    uses: ./.github/workflows/python_workflows.yml
    with:
      config-path: './config/python_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  
  call_publish_workflows:
    uses: ./.github/workflows/quartopublish_workflows.yml
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
