name: Main Workflows

on:
  push:
    branches:
      - main

jobs:
  check_commit_and_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/cli/cli/releases/download/v2.26.1/gh_2.26.1_linux_amd64.tar.gz -o gh.tar.gz
          tar xzf gh.tar.gz
          sudo mv gh_2.26.1_linux_amd64/bin/gh /usr/local/bin/
          gh --version
          
      - name: Clear GH_TOKEN environment variable
        run: |
          unset GH_TOKEN
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check commit message
        run: |
          if [[ "$(git log --format=%B -n 1 HEAD)" != "py_commit" ]]; then
            echo "Proceeding with python_workflows..."
            # Trigger python_workflows.yml
            gh workflow run python_workflows.yml -f config-path='./config/python_config.yml'
          else
            echo "Commit message is 'py_commit'. Triggering quartopublish_workflows..."
            # Trigger quartopublish_workflows.yml
            gh workflow run quartopublish_workflows.yml -f config-path='./config/quarto_config.yml'
          fi
