name: Main Workflows

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 


jobs:
  call_python_workflows:
    uses: ./.github/workflows/python_workflows.yml
    with:
      config-path: './config/python_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 