name: Main Workflows

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:


jobs:
  call_python_workflows:
    uses: Qufst/Workflows_computorg/.github/workflows/python_workflows.yml@main
    with:
      config-path: './config/python_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 
  call_quartopublish_workflows:
    uses: Qufst/Workflows_computorg/.github/workflows/quartopublish_workflows.yml@main
    needs: call_python_workflows
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}