name: Main Workflows

on:
  push:
    branches:
      - main

jobs:
  check_commit_and_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          if [[ "$(git log -1 --pretty=%B)" != "py_commit" ]]; then
            echo "Proceeding with python_workflows..."
            # Trigger python_workflows.yml
            gh workflow run python_workflows.yml -f config-path='./config/python_config.yml'
          else
            echo "Commit message is 'py_commit'. Triggering quartopublish_workflows..."
            # Trigger quartopublish_workflows.yml
            gh workflow run quartopublish_workflows.yml -f config-path='./config/quarto_config.yml'
          fi
