name: Main Workflows

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 


jobs:
  call_python_workflows:
    uses: https://github.com/Qufst/Workflows_computorg/blob/main/python_workflows.yml
    with:
      config-path: './config/python_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 
  call_quartopublish_workflows:
    uses: https://github.com/Qufst/Workflows_computorg/blob/main/quartopublish_workflows.yml
    needs: call_python_workflows
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 