name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Installing dependencies from requirements
        run: |
          pip install -r requirements.txt

      - name: Call Quarto Workflows
        run: |
          gh workflow run quartopublish_workflows.yml -f config-path= './config/quarto_config.yml' -f token=${{ secrets.REPO_DISPATCH_TOKEN }}
