name: python

on:
  repository_dispatch:
    types: [custom-event] 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Create conda environment and install dependencies
        run: |
          conda init
          conda create --yes --name myenv python=3.10
          conda install --file requirements.txt

      - name: Cache conda environment
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: /home/runner/miniconda/envs/myenv
          key: ${{ runner.os }}-conda-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: ls myenv
        run: |
          ls * myenv

      - name: Compress conda environment
        run: |
          tar -czvf myenv.tar.gz -C ./usr/share/miniconda/envs

      - name: Upload conda environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: conda-env
          path: myenv.tar.gz