name: python

on:
  repository_dispatch:
    types: [custom-event] 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up micromamba
        uses: mamba-org/provision-with-micromamba@v1

      - name: recherche de micromamba
        run: |
          ls *
          ls /home/runner/
          ls /home/runner/micromamba

      - name: Cache Micromamba environment
        id: cache-micromamba-env
        uses: actions/cache@v3
        env: 
          cache-name: micromamba
        with:
          path: ~/home/runner
          key: ${{ runner.os }}-micromamba-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-micromamba-${{ env.cache-name }}-
            ${{ runner.os }}-micromamba
            ${{ runner.os }}-

      - name: put in cache
        id: micromamba
        uses: actions/cache@v3
        env:
          cache-name: micromamba2
        with: 
          path: ~/home/runner/micromamba
          key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-micromamba






