name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      config-path:
        description:
        required: true
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
          GITHUB_REPOSITORY_URL: https://x-access-token:${{ secrets.REPO_DISPATCH_TOKEN }}@github.com/Qufst/template-computo-python.git
        run: |
          git clone https://github.com/Qufst/template-computo-python.git
          cd template-computo-python


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
  
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ./abc
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Python dependencies
        run: |
          python -m venv ./abc
          source ./abc/bin/activate
          pip install -r requirements.txt
      
      - name: Save cache key
        run: echo "CACHE_KEY=${{ steps.cache-pip.outputs.cache-hit }}" > $GITHUB_ENV

      - name: Trigger external workflow with empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
        run: |
            git config --local user.email "quentin.festor@etu.umontpellier.com"
            git config --local user.name "Qufst"
            git checkout main
            git commit --allow-empty -m "py_commit"
            git remote set-url origin https://github.com/Qufst/template-computo-python.git
            git push https://github.com/Qufst/template-computo-python origin main
