name: python

on:
  repository_dispatch:
    types: [custom-event] 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: activate
        run: |
          micromamba init
          micromamba activate myenv

      - name: Cache Micromamba installation and environments
        id: cache-micromamba
        uses: actions/cache@v3
        with:
          path: ~/micromamba
          key: ${{ runner.os }}-micromamba-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-micromamba-
            ${{ runner.os }}-







