name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      config-path:
        description:
        required: true
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Create archive of virtual environment
        run: |
          tar -czf python-venv.tar.gz venv
      
      - name: Save Python environment
        uses: actions/upload-artifact@v2
        with:
          name: python-venv
          path: python-venv.tar.gz

      - name: Save Python environment
        uses: actions/upload-artifact@v2
        with:
          name: python-venv
          path: ${{ github.workspace }}/venv

      - name: Call Quarto Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run quartopublish_workflows.yml -f config-path='./config/quarto_config.yml'
