name: python

on:
  repository_dispatch:
    types: [custom-event] 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up micromamba
        uses: mamba-org/provision-with-micromamba@v1

      - name: Cache micromamba environment
        id: cache-micromamba
        uses: actions/cache@v3
        with:
          path: /home/runner/micromamba/envs/myenv
          key: ${{ runner.os }}-micromamba-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-micromamba-

      - name: Compress mamba environment
        run: |
          cd /home/runner/micromamba/envs/
          zip -r env.zip ./myenv

      - name: Upload mamba environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myenv
          path: /home/runner/micromamba/envs/env.zip