name: python

on:
  workflow_dispatch:
    inputs:
      config-path:
        description: "Chemin du fichier de configuration"
        required: true
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create archive of virtual environment
        run: |
          tar -czf python-venv.tar.gz venv

      - name: Save Python environment
        uses: actions/upload-artifact@v2
        with:
          name: python-venv
          path: python-venv.tar.gz
