name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      config-path:
        description:
        required: true
        type: string
  workflow_run:
    workflows: ["python_workflows.yml"]
    types:
      - completed

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
  
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ./abc
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Python dependencies
        run: |
          python -m venv ./abc
          source ./abc/bin/activate
          pip install -r requirements.txt
      
      - name: Save cache key
        run: echo "CACHE_KEY=${{ steps.cache-pip.outputs.cache-hit }}" > $GITHUB_ENV

      - name: Call Quarto Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run quartopublish_workflows.yml -f config-path='./config/quarto_config.yml'
        

