name: python

on:
  repository_dispatch:
    types: [custom-event] 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up micromamba
        uses: mamba-org/provision-with-micromamba@v1

      - name: List micromamba environments
        run: |
          mamba env list

      - name: Cache micromamba environment
        id: cache-micromamba
        uses: actions/cache@v3
        with:
          path: ./env
          key: ${{ runner.os }}-micromamba-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-micromamba-

      - name: Compress conda environment
        run: |
          cd /home/runner/work/template-computo-python/template-computo-python
          zip -r env.zip ./env

      - name: Upload conda environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: micromamba-env
          path: ./env.zip