name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      config-path:
        description:
        required: true
        type: string

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m venv ./abc
          source ./abc/bin/activate
          pip install -r requirements.txt
      

      - name: Archive the environment
        run: |
          zip -r abc.zip ./abc
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./abc.zip

      - name: Trigger external workflow with empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
          GITHUB_REPOSITORY_URL: https://x-access-token:${{ secrets.REPO_DISPATCH_TOKEN }}@github.com/Qufst/template-computo-python.git
        run: |
          git config --global user.email "quentin.festor@etu.umontpellier.fr"
          git config --global user.name "Qufst"
          git checkout main
          git commit --allow-empty -m "py_commit"
          git remote set-url origin https://github.com/Qufst/template-computo-python.git
          git push origin main
