name: python

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      config-path:
        description:
        required: true
        type: string
  workflow_run:
    workflows: ["python_workflows.yml"]
    types:
      - completed

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ./venv  
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Compress virtual environment
        run: |
          zip -r venv.zip ./venv

      - name: Upload virtual environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-venv
          path: venv.zip

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/cli/cli/releases/download/v2.26.1/gh_2.26.1_linux_amd64.tar.gz -o gh.tar.gz
          tar xzf gh.tar.gz
          sudo mv gh_2.26.1_linux_amd64/bin/gh /usr/local/bin/
          gh --version
  
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Trigger Quarto Publish Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run quartopublish_workflows.yml -f config-path='./config/quarto_config.yml'



        

